version: '3.7'
services:
  isesame_music:
    build: .
    image: isesame_music
    container_name: isesame_music
    environment:
      - "APP_PROJECT=hyperf"
      - "APP_ENV=test"
    ports:
      - 9501:9501
      - 9502:9502
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
#    networks:
#      - hyperf_net
    configs:
      - source: hyperf_v1.0
        target: /var/www/.env
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis:latest
    container_name: isesame_music_redis
    ports:
      - 63790:6379
configs:
  hyperf_v1.0:
    external: true
#networks:
#  hyperf_net:
#    external: true
